### ISSUE TITLE
status code naming convention

### ISSUE THREAD

**Issue by rumca-js** [apify/crawlee-python#352]
Status code can be obtained using BeautifulSoupCrawler/BeautifulSoupCrawlingContext
   context.http_response.status_code

Status code can be obtained using PlaywrightCrawler/PlaywrightCrawlingContext
   context.response.status

PlaywrightCrawlingContext and BeautifulSoupCrawlingContext use same naming convention for status code?

**Comment by janbuchar** [comment]
Hello, and thanks for your interest in Crawlee! I'm not sure if I understand your question. While we do try to make a uniform interface for various crawlers, we try to strike a balance between wrapping APIs for uniformity and keeping familiar APIs the same so that if you know Playwright, for instance, you can use it in Crawlee just the way you're used to.

Did I answer your question?

**Comment by rumca-js** [comment]
Oh, I understand that now.
Playwright indeed provides response.status (https://playwright.dev/docs/api/class-response).

Thanks.
